### ISSUE TITLE
Question about the absolute evaluation angles

### ISSUE THREAD

**Issue by JiajieLi7012** [SUDO-AI-3D/zero123plus#101]
Hi, thanks for your great work. I am confused about the absolute evaluation angles of the generated images. I don't understand what xy-plane determines these absolute evaluation angles. Any insight would be appreciated.

**Comment by eliphatfs** [comment]
The model decides the gravity direction in the input image, and derives the plane implicitly.

**Comment by JiajieLi7012** [comment]
I see. Thanks for your explanation.
