### ISSUE TITLE
macbook pro pip install error

### ISSUE THREAD

**Issue by jiechengyang** [SUDO-AI-3D/zero123plus#102]
0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/zstd-sys-5b86feba3143f6b8/out -L native=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/esaxx-rs-e3fce1de8945526c/out -L native=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/onig_sys-76c3c5f87b7344d6/out`
      warning: variable does not need to be mutable
         --> tokenizers-lib/src/models/unigram/model.rs:265:21
          |
      265 |                 let mut target_node = &mut best_path_ends_at[key_pos];
          |                     ----^^^^^^^^^^^
          |                     |
          |                     help: remove this `mut`
          |
          = note: `#[warn(unused_mut)]` on by default

      warning: variable does not need to be mutable
         --> tokenizers-lib/src/models/unigram/model.rs:282:21
          |
      282 |                 let mut target_node = &mut best_path_ends_at[starts_at + mblen];
          |                     ----^^^^^^^^^^^
          |                     |
          |                     help: remove this `mut`

      warning: variable does not need to be mutable
         --> tokenizers-lib/src/pre_tokenizers/byte_level.rs:200:59
          |
      200 |     encoding.process_tokens_with_offsets_mut(|(i, (token, mut offsets))| {
          |                                                           ----^^^^^^^
          |                                                           |
          |                                                           help: remove this `mut`

      error: casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
         --> tokenizers-lib/src/models/bpe/trainer.rs:526:47
          |
      522 |                     let w = &words[*i] as *const _ as *mut _;
          |                             -------------------------------- casting happend here
      ...
      526 |                         let word: &mut Word = &mut (*w);
          |                                               ^^^^^^^^^
          |
          = note: for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
          = note: `#[deny(invalid_reference_casting)]` on by default

      warning: `tokenizers` (lib) generated 3 warnings
      error: could not compile `tokenizers` (lib) due to 1 previous error; 3 warnings emitted

      Caused by:
        process didn't exit successfully: `/Users/jiechengyang/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name tokenizers --edition=2018 tokenizers-lib/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="cached-path"' --cfg 'feature="clap"' --cfg 'feature="cli"' --cfg 'feature="default"' --cfg 'feature="dirs"' --cfg 'feature="esaxx_fast"' --cfg 'feature="http"' --cfg 'feature="indicatif"' --cfg 'feature="onig"' --cfg 'feature="progressbar"' --cfg 'feature="reqwest"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("cached-path", "clap", "cli", "default", "dirs", "esaxx_fast", "fancy-regex", "http", "indicatif", "onig", "progressbar", "reqwest", "unstable_wasm"))' -C metadata=7c0a382785cac3b2 -C extra-filename=-7c0a382785cac3b2 --out-dir /private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps -C strip=debuginfo -L dependency=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps --extern aho_corasick=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libaho_corasick-237707a7779771fa.rmeta --extern cached_path=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libcached_path-fcbeddc230a1c6f2.rmeta --extern clap=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libclap-8a4c65accd2b5f69.rmeta --extern derive_builder=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libderive_builder-e67f39fcfda677c5.rmeta --extern dirs=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libdirs-91f665484bb16308.rmeta --extern esaxx_rs=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libesaxx_rs-0855befd5b0b97de.rmeta --extern getrandom=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libgetrandom-cb438be93bafba4c.rmeta --extern indicatif=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libindicatif-4b3ce9b85d64f167.rmeta --extern itertools=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libitertools-555049cbe5ad6976.rmeta --extern lazy_static=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/liblazy_static-bdbcb74940987b6d.rmeta --extern log=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/liblog-1d2ad8bd0820403b.rmeta --extern macro_rules_attribute=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libmacro_rules_attribute-b7449b2a37320fd0.rmeta --extern monostate=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libmonostate-1acdcaec4a81b122.rmeta --extern onig=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libonig-6692079bbc06bff7.rmeta --extern paste=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libpaste-ccb893d2ca80bda6.dylib --extern rand=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/librand-cc3838fdcbee911e.rmeta --extern rayon=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/librayon-922e5e90735d5b48.rmeta --extern rayon_cond=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/librayon_cond-d5b95f24caa29ea9.rmeta --extern regex=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libregex-1d066c28fd813d98.rmeta --extern regex_syntax=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libregex_syntax-0da993eb8a1d533f.rmeta --extern reqwest=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libreqwest-b4ec1c2283f313ff.rmeta --extern serde=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libserde-214a3a61f0dfd505.rmeta --extern serde_json=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libserde_json-c8da7187e6c36e17.rmeta --extern spm_precompiled=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libspm_precompiled-90022e7600d9b05c.rmeta --extern thiserror=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libthiserror-33ead20d5d275772.rmeta --extern unicode_normalization_alignments=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libunicode_normalization_alignments-de97bd3188c9170d.rmeta --extern unicode_segmentation=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libunicode_segmentation-922fb58698c75f4b.rmeta --extern unicode_categories=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/deps/libunicode_categories-b7dc78fdf4f9a9f7.rmeta -L native=/usr/lib -L native=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/zstd-sys-5b86feba3143f6b8/out -L native=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/esaxx-rs-e3fce1de8945526c/out -L native=/private/var/folders/kc/1gkzd_gd4m32y11_qqj_pvmh0000gn/T/pip-install-_xn1s5aq/tokenizers_125ddadb7acf4d949997e24fc57a307d/target/release/build/onig_sys-76c3c5f87b7344d6/out` (exit status: 1)
      warning: build failed, waiting for other jobs to finish...
      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib -- -C 'link-args=-undefined dynamic_lookup -Wl,-install_name,@rpath/tokenizers.cpython-312-darwin.so'` failed with code 101
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Successfully built segment_anything
Failed to build tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)

**Comment by eliphatfs** [comment]
This is related to an upstream repository https://github.com/huggingface/tokenizers and we don't manage it. You may create an issue there.
