### ISSUE TITLE
你们是来搞笑的吗？

### ISSUE THREAD

**Issue by stone100010** [SUDO-AI-3D/zero123plus#19]
![image](https://github.com/SUDO-AI-3D/zero123plus/assets/48286567/f662b36e-e6ff-4312-b296-87608770f527)

冰墩墩给弄成了这样，哈哈哈哈

**Comment by eliphatfs** [comment]
Generative models can fail sometimes.

**Comment by ootts** [comment]
In general, a generative model may produce different results at different runs or with different random seeds. The following is an example result with rescale=True and seed=777.
<img width="749" alt="image (8)" src="https://github.com/SUDO-AI-3D/zero123plus/assets/24546823/aff11d04-bf58-478c-8ee1-b6160d3cdd77">
