### ISSUE TITLE
about FOV for rendering dataset

### ISSUE THREAD

**Issue by badlooop** [SUDO-AI-3D/zero123plus#39]
Firstly, thank you so much for sharing such an impressive work!

I'd like to know the FOV you used when rendering the training data. This way, I can quickly integrate my rendered content into new viewpoint generation, thereby achieving texture mapping. 

Thank you very much!

**Comment by eliphatfs** [comment]
The FOV is 47.1 degrees (`arctan(32 / 2 / 35) * 2`).
