### ISSUE TITLE
data of depth ControlNet

### ISSUE THREAD

**Issue by staymylove** [SUDO-AI-3D/zero123plus#40]
Dear author:
  I want to ask the format of data of depth ControlNet must be 6 subfigures?  I think it is hard to get the multiview depth image.

**Comment by eliphatfs** [comment]
I think in general you will need to know the geometry beforehand. After that you can render linear depth of the geometry (defined as distance to the camera plane) and perform a normalization:

```python
def process_depth(self, x):
    mask = x.r > 0.001
    alpha = mask.float()
    if not mask.any():
        n = x * 0
    else:
        v = x[mask]
        n = (x - v.min()) / (v.max() - v.min() + 1e-9)
    return float4(n, n, n, alpha)
```

**Comment by staymylove** [comment]
Thanks for your reply. Actually, I want to ask when I use depth ControlNet, my input should be 6 multiviews depth image or just single depth image?
example is :
![image](https://github.com/SUDO-AI-3D/zero123plus/assets/77335979/f88dffd3-0fe0-4398-b859-cbe1dba903ca)

But I want to ask single image + single depth image like the depth image below  can get the same output?
![image](https://github.com/SUDO-AI-3D/zero123plus/assets/77335979/9443da3b-0504-4554-87c3-60cbda7eae9d)

**Comment by eliphatfs** [comment]
No you'll have to provide 6 images.

**Comment by eliphatfs** [comment]
It may be possible to train another ControlNet on the contioning reference attention branch, but the released version is not about that.

**Comment by kpister** [comment]
I'm confused about this. Isn't the purpose of this project to generate the 6 image views? If I had depth estimates of the 6 views, why do I need to synth the views again?

Perhaps I am misunderstanding. Thank you for your work and patience.

**Comment by eliphatfs** [comment]
Yes; but for example, you have a 'white model' without any textures, then the controlnet can help you generate texture on the model. That's the point of the released ControlNet.
