### ISSUE TITLE
How to get the textured mesh?

### ISSUE THREAD

**Issue by wqdong8** [SUDO-AI-3D/zero123plus#46]
hi, great work!
I want to know how to get the final mesh from the generated multi view image? Like One-2-3-45, use SparseNeuS?

**Comment by Dustinpro** [comment]
Thanks! We just released [One-2-3-45++](https://sudo-ai-3d.github.io/One2345plus_page/), which uses Zero123++ as the multiview generation module. You can find the interactive demo at https://www.sudo.ai/3dgen, where you can get a mesh from a single image or a text prompt.

**Comment by wqdong8** [comment]
Thank you for your reply. I have tried the SUDO-ai Image-to-3D, but the generated mesh seems to have some artifacts, for example, holes. Is there any way to solve it?

![front_rgba](https://github.com/SUDO-AI-3D/zero123plus/assets/60336566/57a8e884-4d05-4162-88ed-d3277e836da8)

![下载 (3)](https://github.com/SUDO-AI-3D/zero123plus/assets/60336566/e108c9f1-0e01-4250-bea7-beafd9d7c52d)

<img width="423" alt="image" src="https://github.com/SUDO-AI-3D/zero123plus/assets/60336566/8c99526d-4b82-4cd0-9a6f-5db23e097e07">

**Comment by Dustinpro** [comment]
It is a stochastic process, so giving it another try may result in a better mesh.
<img width="712" alt="Screenshot 2023-11-15 at 01 37 14" src="https://github.com/SUDO-AI-3D/zero123plus/assets/23076389/0be3681a-3e9e-4b48-9574-45b1c92607b8">

**Comment by wqdong8** [comment]
Wow, thanks !
