### ISSUE TITLE
Questions of camera settings when rendering the Objaverse dataset

### ISSUE THREAD

**Issue by HansenHuang0823** [SUDO-AI-3D/zero123plus#47]
Thanks for your great work! But I have questions of rendering the Objaverse dataset. What's the camera intrinsic matrix? And what is the camera distance?

**Comment by eliphatfs** [comment]
The camera FOV is 47.1 degrees, and principal point is the center of screen.

**Comment by HansenHuang0823** [comment]
Thank you for you fast reply!
