### ISSUE TITLE
Not generating input image's colors when depth maps passed

### ISSUE THREAD

**Issue by pragyavaishanav** [SUDO-AI-3D/zero123plus#49]
Hello Authors, first of all thanks so much for the amazing work. 
I am trying to run zero123plus pipeline with depth control net.  When I use the depth_image, then the input image's pixels/colors are completely disregarded by the model. The model still generate (kind of) consistent 6 images with respect to depth, but the initial input image colors are no where to be seen. 
I tested with your blue and yellow kid chair and one of my test models. I am sharing the pipeline and as well as the input and output results. It'd be a great help for me if you can look into this. 
`
pipeline = DiffusionPipeline.from_pretrained(
    "sudo-ai/zero123plus-v1.1", custom_pipeline="sudo-ai/zero123plus-pipeline",
    torch_dtype=torch.float16
)
pipeline.add_controlnet(ControlNetModel.from_pretrained(
    "sudo-ai/controlnet-zp11-depth-v1", torch_dtype=torch.float16
), conditioning_scale=0.75)

pipeline.scheduler = EulerAncestralDiscreteScheduler.from_config(
    pipeline.scheduler.config, timestep_spacing='trailing'
)
pipeline.to('cuda:0')

result = pipeline(cImage, depth_image=dImage,  num_inference_steps=35).images[0]

`

![0_cond](https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/12f12557-0331-4034-b27e-cbc978c38288)
![0_depth](https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/8e5eac04-1f56-4263-80c5-1139bd70fe84)

<img width="275" alt="Screen Shot 2023-11-23 at 12 49 46 PM" src="https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/933a4c31-d566-46ae-9511-6442238c1098">

![4_image (8)](https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/9baf1080-d4f9-4f51-bfd7-960bc8aa6bfc)
![master_depth](https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/888e649a-52a8-46ce-875b-7ff13f064321)
<img width="185" alt="Screen Shot 2023-11-23 at 12 54 13 PM" src="https://github.com/SUDO-AI-3D/zero123plus/assets/40742845/f20a37e9-3277-445e-93f9-4b29150c437d">

**Comment by pragyavaishanav** [comment]
I found the solution. The scheduler doesnt work when you wish to use depth maps. Use something else or just comment it out and it will work.

**Comment by eliphatfs** [comment]
What version of diffusers are you using? The snippet works on my side.
