### ISSUE TITLE
How can I change the camera pose and the size of the image?

### ISSUE THREAD

**Issue by donghaotian123** [SUDO-AI-3D/zero123plus#57]
Hello, thank you very much for releasing your code. I couldn't find a specific part in the code that defines the camera pose. May I ask how you trained or inferred to get images of the corresponding 6 poses? Did you create such a dataset yourself? If I want to generate images from other angles, do I need to create my own dataset? Additionally, I would like to know how to change the size of the generated images. I look forward to your reply, thank you!

**Comment by eliphatfs** [comment]
The network is trained to generate a fixed set of non-ambiguous poses. Please refer to the report.

**Comment by eliphatfs** [comment]
I think you need to retrain the network or at least finetune to generate images from other angles or change the size.
