### ISSUE TITLE
question about forward_cond

### ISSUE THREAD

**Issue by ZZWENG** [SUDO-AI-3D/zero123plus#58]
Hi, thank you for the great work! I have a question about the forward_cond function under the RefOnlyNoisedUNet class. Why is it necessary to call it in the forward function? What does it achieve?
Thank you!

https://github.com/SUDO-AI-3D/zero123plus/blob/main/diffusers-support/pipeline.py#L134

**Comment by eliphatfs** [comment]
It is the implementation of the Reference Attention mechanism. We forward UNet on the condition branch and record the KV matrices in the attention processor, then forward UNet on the denoising branch and concat the recorded KV matrices.

**Comment by ZZWENG** [comment]
thanks
