### ISSUE TITLE
 getting normals/depth

### ISSUE THREAD

**Issue by fefespn** [SUDO-AI-3D/zero123plus#62]
Hey,

I wanted to ask, is there a way in the current implantations to get the normals or depth for the generated view (or the inserted image) ?

**Comment by eliphatfs** [comment]
Not yet.

**Comment by eliphatfs** [comment]
We are planning to release a normal generator soon, please stay tuned!

**Comment by eliphatfs** [comment]
We have released v1.2 which includes a normal generator.

**Comment by kevinhuangxf** [comment]
Hello. I can get the normal map with the normal generator, but how can I get the depth output from the zero123plus model?
To be more specific, we have an in-the-wild image and I don't have any depth prior. I want to obtain the depth maps output for the generated multiple views.
