### ISSUE TITLE
Is there an approach to remove the gray background purely?

### ISSUE THREAD

**Issue by bluestyle97** [SUDO-AI-3D/zero123plus#64]
Thanks for your valuable work! But I'm wondering why zero123++ generates images with a gray background, which leads to much inconvience when feeding the synthesized multiview images to image-to-3D reconstruction pipelines such as OpenLRM or NeuS (Also, Instant3D if it's open-sourced in the future), since most of these methods require a white background for the input images. Using the `rembg` package to remove the gray background leads to inconsistent and wrong segmentations especially when there are image regions close to the gray color. So I'm wondering if there is an approch to remove the gray background purely and generate consistent white-background images? Also, I'm curious about whether you directly feed the gray-background images to the 3D diffusion model as conditions as described in the One2345++ paper?

**Comment by Time-Lord12th** [comment]
Same question here. Will the image be preprocessed as a gray background during training?
![image](https://github.com/SUDO-AI-3D/zero123plus/assets/53140195/7e5794c7-00a4-4a55-a42a-cef075afdbc2)

**Comment by eliphatfs** [comment]
> Same question here. Will the image be preprocessed as a gray background during training? ![image](https://private-user-images.githubusercontent.com/53140195/299876750-7e5794c7-00a4-4a55-a42a-cef075afdbc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTA5NDUsIm5iZiI6MTcwNjQxMDY0NSwicGF0aCI6Ii81MzE0MDE5NS8yOTk4NzY3NTAtN2U1Nzk0YzctMDBhNC00YTU1LWE0MmEtY2VmMDc1YWZkYmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAyNTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZGQzNzdhNjk3ZTQyOTZhMjU1NjhmOWI3NjI2N2FmNTcxY2I1OGQ2MjZmZDE3Yjk0ZmJhMTEzMjU5NWQzMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wCvUrexYOIqHQ_ySEOhenZMK_TtIGpMhcPgOqbPvjXw)

Yes.

**Comment by eliphatfs** [comment]
The background can be removed with SAM, better than rembg; you can check the demo code for details.
The IoU is in general about 96%, which is good but admittedly not perfect.
We are planning to release a new version of the model that deals with the issue, but before that we can do few about it.

And yes, for One2345++ we feed gray background images to the 3D diffusion model during training, so there is no gap here.

**Comment by eliphatfs** [comment]
We released v1.2 that has a normal-based approach for alpha mask prediction. Note that the approach is not suitable for semi-transparent objects, only pure opaque ones.

**Comment by vidit98** [comment]
Hi, what background color is used in condition images during training? Is it random? because I see during inference there is no background processing done for input image

**Comment by eliphatfs** [comment]
it is only grey; for non-grey backgrounds the diffusion model could generalize but controlnet may wrongly interpret it.

**Comment by vidit98** [comment]
I see, interesting!
