### ISSUE TITLE
camera pose

### ISSUE THREAD

**Issue by donghaotian123** [SUDO-AI-3D/zero123plus#65]
Are the new perspective images rendered in blender? Can you provide a specific rotation matrix to facilitate calculation of the camera pose?

**Comment by donghaotian123** [comment]
I try to render in blender and got the following calculation method for the new camera pose. I don’t know if this is correct. Of course, I know that if you use blender to render directly, you don't actually need a specific camera pose, you just need to set it directly in blender. But this is very important for my downstream tasks.
![pose](https://github.com/SUDO-AI-3D/zero123plus/assets/43373870/e7fd5e96-cb89-4c36-a787-a5e09615e16c)

**Comment by eliphatfs** [comment]
Sorry but I don't quite understand your question.
The training data is rendered in blender.
