### ISSUE TITLE
camera FOV

### ISSUE THREAD

**Issue by rfeinman** [SUDO-AI-3D/zero123plus#68]
What field of view (FOV; fovy) do you use to render the 6 camera views? I see the elevation and azimuth parameters, but I cannot find the FOV. Thanks!

**Comment by eliphatfs** [comment]
See updates v1.2 and camera parameters section in README. For v1.1 it is the same as Zero-1-to-3 which is `49.13434264120263` degrees or `atan(16 / 35) * 2`.
