### ISSUE TITLE
About the object normalization in v1.2

### ISSUE THREAD

**Issue by bluestyle97** [SUDO-AI-3D/zero123plus#73]
Hi, I notice that the v1.2 model "always outputs a set of views assuming a normalized object size instead of changing w.r.t. the input". Could you please give more explanation on how you normalize the object when rendering the data? Did you set a fixed camera distance for the 6 views? If yes, what's the value?

**Comment by Dustinpro** [comment]
It is normalized to fit into a sphere with radius=.5. The fixed camera distance is `0.5 / np.tan(np.radians(30/2))`.

**Comment by bluestyle97** [comment]
@Dustinpro Thanks for your reply!

**Comment by WilliamHaiweiGu** [comment]
@Dustinpro But if the camera distance is `radius / np.tan(np.radians(30/2))`, there will be a part of the sphere not in the FOV (the black area in the graph below)
![image](https://github.com/user-attachments/assets/c81949bb-ccb3-45ba-bfce-ab87da8fa4b0)
So is the distance `radius / np.sin(np.radians(30/2))`?

**Comment by eliphatfs** [comment]
Yes, there might be a part not in the FOV. This is by design as a data distribution augmentation to enhance the capabilities of the model.

**Comment by eliphatfs** [comment]
I apologize for misunderstanding the question as this is the output. There might be a part not in the FOV, but for most objects, they do not look like spheres, or is not that like spheres. They are thus still fully visible in the FOV. This makes pixel utility and hence effective resolution higher for most objects. For spheres there will be a small part outside the FOV.
