### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by kireoxdz** [SUDO-AI-3D/zero123plus#79]
I am a new researcher.  Can you provide me with a case for each of the ’‘objaverse-xl’‘ and ’‘objaverse-1.0’‘? The original data is too large to download. Thank you

**Comment by eliphatfs** [comment]
You can download examples [here](https://huggingface.co/datasets/allenai/objaverse/tree/main/glbs/000-000) without downloading the whole dataset. I also kindly redirect your request to the Objaverse authors; this is off-topic here.
