### ISSUE TITLE
Question about the input single image

### ISSUE THREAD

**Issue by ingra14m** [SUDO-AI-3D/zero123plus#8]
Hi, thank you for your outstanding work. 

I have always had a question regarding the 'Single Image to 3D' tasks. I've noticed that almost all images input into these systems are in a front-facing and upright position. I'm uncertain if I would get equally perfect results when inputting images that are viewed from the bottom or upside down. I believe these latter cases could play a crucial role in many completion tasks.

**Comment by eliphatfs** [comment]
We only trained the model with input elevation angles between -45 and 60 degrees, so it would not be able to take views from extreme bottom. For most objects in the world, viewing from bottom gives very limited information about what the object is and how it looks like, so the problem would be a little ill-defined.

**Comment by ingra14m** [comment]
Thanks for your prompt reply!!
