### ISSUE TITLE
The difference between v1.2 and v1.1 in the network architecture

### ISSUE THREAD

**Issue by Ping-Hu** [SUDO-AI-3D/zero123plus#81]
Thank you for releasing v1.2 with support for normal generation! I'm wondering what is the network architecture difference between v1.2 and v1.1? According to the commit history of "pipeline.py" and configs in the directory, diffusers_support, it seems that the customized pipeline is not changed in v1.2. Am I correct?
Thank you for your attention!

**Comment by eliphatfs** [comment]
No, the network architecture didn't change. The data changed.
