### ISSUE TITLE
DLL load failed while importing libtriton

### ISSUE THREAD

**Issue by knuthnads** [SUDO-AI-3D/zero123plus#85]
Tried running gradio_app.py and it failed with the following error:

_ImportError: DLL load failed while importing libtriton: The specified module could not be found._

I have torch v2.1, diffusers v0.20.2, and transformers 4.29.2. Installed requirements.txt without any errors.

**Comment by knuthnads** [comment]
The bitsandbytes library was interfering. Removing it fixed the problem.

**Comment by eliphatfs** [comment]
Looks like a problem with integration of diffusers library and not ours.
