### ISSUE TITLE
Download model error.

### ISSUE THREAD

**Issue by shirleyanan** [SUDO-AI-3D/zero123plus#87]
Hello, when i run:

```
from diffusers import DiffusionPipeline
pipeline = DiffusionPipeline.from_pretrained("sudo-ai/zero123plus-v1.2")
```
I get the following error:
`requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sudo-ai/zero123plus-v1.2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8838664cd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: 105c1a1b-03f6-4060-8a31-a98910b5f9a4)')`

Any idea why?

**Comment by eliphatfs** [comment]
Your internet does not connect to huggingface. Likely you are doing wrong with your proxy config or huggingface was temporarily down in your region at that time.

**Comment by shirleyanan** [comment]
May I ask if there is any other way to use Zero123plus without huggingface.



Li Xiang
South China Agricultural University
---- Replied Message ----
| From | ***@***.***> |
| Date | 6/14/2024 02:25 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [SUDO-AI-3D/zero123plus] Download model error. (Issue #87) |

Your internet does not connect to huggingface. Likely you are doing wrong with your proxy config or huggingface was temporarily down in your region at that time.

**Comment by eliphatfs** [comment]
Sorry but our code depends heavily on huggingface diffusers.
