### ISSUE TITLE
About computation resources

### ISSUE THREAD

**Issue by qwer1793** [SUDO-AI-3D/zero123plus#89]
I notice that the paper didn't mention the computation resources, I'm quite interested in training a Depth ControlNet for Zero123++ on myself with only have 4 RTX3090s. Is it enough to train?

**Comment by eliphatfs** [comment]
You can do a ControlNet on a single 2080Ti if you want. ControlNets usually converge with a batch size as small as 4, and sudden converges in about 10k-20k steps. This would be about 2 days on an 2080Ti :)
To get the best results you need a batch size of 128-256 and train for 30k steps. In that case we would recommend 8xA100 or more setup.

**Comment by eliphatfs** [comment]
With small batch size the model would also be usable in general, but may be slightly less clever towards some of the control images.
