### ISSUE TITLE
How to get the depth map output?

### ISSUE THREAD

**Issue by kevinhuangxf** [SUDO-AI-3D/zero123plus#91]
Thanks for the fantastic work.

Accoding to the latest release I can get the normal map output.

Instead of using depth map prior, I wonder how can I get the depth map output for the generated multiple views?

I've tried transfer normal maps to depth maps but the results are inaccurate.

**Comment by eliphatfs** [comment]
Depth is an absolute-valued modality unlike normals. Thus, the dynamic range of a natural image is not enough to encode useful information in depths.

**Comment by eliphatfs** [comment]
Basically, you have to use another model upon the multi-view images for other kinds of prior that can get depths for you.

**Comment by kevinhuangxf** [comment]
Thank you so much for your prompt response. I'm trying to using depth estimation model based on the multi-view images. I just wonder if there is a "ground truth" depth from the zero123plus model.
