### ISSUE TITLE
reconstruction question

### ISSUE THREAD

**Issue by Dumeowmeow** [SUDO-AI-3D/zero123plus#98]
Hi, thanks for your great work!
I want to use the six generated images to reconstruct 3D gaussians. And I need to know the camera parameters of these images.They contain [azimuths, elevations, radius, fovx, fovy, near, far], I know that the azimuths and elevations are as follows:
azimuths = np.array([30, 90, 150, 210, 270, 330]).astype(float)
elevations = np.array([20, -10, 20, -10, 20, -10]).astype(float)
May I ask how to set the other parameters?

**Comment by eliphatfs** [comment]
FOV is documented in https://github.com/SUDO-AI-3D/zero123plus?tab=readme-ov-file#camera-parameters
Radius/near/far are up to your choices. The values are equivariant to the object size. So if you use a larger radius the reconstructed object would be larger, and vice versa. For near/far you can set to common values in gaussians.

**Comment by Dumeowmeow** [comment]
> FOV is documented in https://github.com/SUDO-AI-3D/zero123plus?tab=readme-ov-file#camera-parameters Radius/near/far are up to your choices. The values are equivariant to the object size. So if you use a larger radius the reconstructed object would be larger, and vice versa. For near/far you can set to common values in gaussians.

Can we generate more than 6 images, or do we need to retrain or change the model architecture?

**Comment by eliphatfs** [comment]
You will need to retrain. Or fine-tune at least.

**Comment by JiajieLi7012** [comment]
> Hi, thanks for your great work! I want to use the six generated images to reconstruct 3D gaussians. And I need to know the camera parameters of these images.They contain [azimuths, elevations, radius, fovx, fovy, near, far], I know that the azimuths and elevations are as follows: azimuths = np.array([30, 90, 150, 210, 270, 330]).astype(float) elevations = np.array([20, -10, 20, -10, 20, -10]).astype(float) May I ask how to set the other parameters?

Hello, I'm also trying to use these images for 3DGS. But I'm a little confused about the radius parameter you listed. Could you please tell me how it's used for the camera intrinsic or pose? Thanks in advance.

**Comment by eliphatfs** [comment]
Assuming the object is normalized to the unit sphere, the radius is the distance from the camera to the origin.

**Comment by JiajieLi7012** [comment]
> Assuming the object is normalized to the unit sphere, the radius is the distance from the camera to the origin.

Thanks.
