### ISSUE TITLE
Is there a plan to add normal control to v1.2?

### ISSUE THREAD

**Issue by goldoak** [SUDO-AI-3D/zero123plus#99]
Is there a plan to add normal control (not the current normal generator) in version 1.2 or later? Additional geometry constraints for multi-view image generation would be quite beneficial.

**Comment by eliphatfs** [comment]
No; we found normal control is prone to overfitting in geometry detail alignment and cannot generalize to estimated normals or work well with generated geometry, and tend to produce flat colors if there is no detail in given normal images. If you have your data and/or ways to work around the generalization problem it won't be hard to train a normal controlnet yourselves.
